name: deploy-code

on:
  push:
    branches:
      - prod # Change this to your main branch

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          path: 'repo1'
          ref: prod
          persist-credentials: false

      - name: Delete Repo2
        run: |
          rm -rf repo2

      - name: Clone Repo2
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/DivyJain23/repo2.git
          cd repo2
          git checkout main

      - name: Copy code from repo1 to repo2
        run: |
          cp -r repo1/* repo2/

      - name: Commit and push changes to Repo2
        run: |
          cd repo2
          git add .
          git commit -m "Update from repo1 ($(date))"
          git push origin main
