name: Sync Repos

on:
  push:
    branches:
      - prod  # Trigger the workflow when changes are pushed to the prod branch of Repo1

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo1
          ref: prod
          token: ${{ secrets.DEPLOY_TOKEN }}
      
      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2
          ref: main
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Pull changes from Repo1
        run: |
          cd repo1
          git pull origin prod

      - name: Push changes to Repo2
        run: |
          cd repo2
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git pull ../repo1 prod --rebase
          git push origin main
