name: CI

on:
  push:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: creates output
        run:  sh ./build.sh
      - name: Pushes to another repository
        run: |
          git config --global user.email "divyjain161@gmail.com"
          git config --global user.name "DivyJain23"
          git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/DivyJain23/repo2.git
          cd repo2
          cp -r ../repo1/* ./
          git add .
          git commit -m "Update from repo1 ($(date))"
          git push origin HEAD:main
