name: Sync Repos

on:
  push:
    branches: [ prod ]  # Optional: Trigger on any push to prod

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          repository: bs-divy-jain/repo-1  # Ensure correct name
          ref: prod
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2
          ref: main

      - name: Pull changes from Repo1
        run: |
          cd repo-1
          git pull origin prod

      - name: Push changes to Repo2 (rebase)
        run: |
          cd repo2
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git pull --rebase ../repo-1 prod
          git push origin main

