name: Push to Repo2 on Prod Merge

on:
  push:
    branches:
      - prod

jobs:
  push_to_repo2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2

      - name: Install GitHub CLI and configure authentication
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        run: |
          sudo apt update
          sudo apt install curl
          curl -fsSL https://cli.github.com/packages/releases/latest/download/gh-linux-x86_64 -o gh
          chmod +x gh
          mv gh /usr/local/bin/
          gh auth login --with-token ${{ secrets.DEPLOY_TOKEN }}
      
      - name: Clone Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          path: ./repo2

      - name: Push changes to Repo2 (prod branch)
        working-directory: ./repo2
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git pull origin prod --ff-only
          git push origin prod
