name: Push to Repo2

on:
  push:
    branches:
      - prod

jobs:
  push_to_repo2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
      
      - name: Clone Repo2
        run: git clone https://github.com/DivyJain23/repo2.git repo2

      - name: Copy changes to Repo2
        run: cp -r * repo2/

      - name: Commit and Push to Repo2
        working-directory: ./repo2
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated commit: Sync changes from Repo1"
          git push
