name: deploy-code

on:
  push:
    branches:
      - prod # Change this to your main branch

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          path: 'repo1'
          ref: prod
          persist-credentials: false
      
      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: 'repo2'
          ref: main
          persist-credentials: true
          fetch-depth: 0  # Fetch the entire history of the branch

      - name: Update dev branch with changes from prod branch
        shell: bash
        working-directory: repo2
        run: |
          git config --global user.email "divyjain161@gmail.com"
          git config --global user.name "DivyJain23"
          git fetch --unshallow origin
          git pull ../repo1 prod
          git add .
          git commit -m "Took latest pull from repo1 dev"
          git push origin Head:main
