name: deploy-code

on:
  push:
    branches:
      - prod # Change this to your main branch

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          path: 'repo1'
          ref: prod
          persist-credentials: false
      
      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          token: ${{secrets.DEPLOY_TOKEN}}
          path: 'repo2'
          ref: main
          persist-credentials: true

      - name: Copy common files to new repo
        shell: bash
        run: |
          cp -r repo1/* repo2/

      - name: Check for new files
        id: newFiles
        shell: bash
        working-directory: repo2
        run: |
          git add .
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=hasNewFiles::true"
          else
            echo "::set-output name=hasNewFiles::false"
          fi
      - name: Push new files
        if: ${{ steps.newFiles.output.hasNewFiles == true}}
        shell: bash
        working-directory: repo2
        run: |
          git config --global user.email "divyjaiin161@gmail.com"
          git config user.name "DivyJain23"
          git commit -m "Update from repo1 ($(date))"
          git push origin HEAD:main
