name: deploy-code

on:
  push:
    branches:
      - prod # Change this to your main branch

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
      
      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          path: repo2

      - name: Copy code from repo1 to repo2
        run: |
          cp -r * repo2/
          cd repo2
          git config user.email "divyjaiin161@gmail.com"
          git config user.name "DivyJain23"
          git add .
          git commit -m "Update from repo1 ($(date))"
          git push origin HEAD:prod
