name: deploy-code

on:
  push:
    branches:
      - prod # Change this to your main branch

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          token: ${{secrets.DEPLOY_TOKEN}}
          path: 'repo2'
          ref: main
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Add origin and pull latest changes
        run: |
          cd repo2/
          git remote remove origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/bs-divy-jain/repo-1.git
          git remote add origin2 https://${{ secrets.DEPLOY_TOKEN }}@github.com/bs-divy-jain/repo-1.git
          git remote remove origin2 https://${{ secrets.DEPLOY_TOKEN }}@github.com/bs-divy-jain/repo-1.git
          git pull origin2 prod

      - name: Commit and push changes
        run: |
          git remote add origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/DivyJain23/repo2.git
          git add .
          git commit -m "Took latest pull from repo1 dev"
          git push origin HEAD:main
