name: Deploy to Repo 2

on:
  push:
    branches:
      - prod

jobs:
  deploy_to_repo2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Push code to Repo 2
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO2 }}
          branch: main
          repository: DivyJain23/repo2
