name: Push to Repo2 on Prod Merge

on:
  push:
    branches:
      - prod

jobs:
  push_to_repo2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install required action and Configure authentication
        uses: apps/app-auth@v2  # Using the official GitHub Apps action
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          gh auth login --with-token  # Using the gh CLI from the GitHub Apps action

      - name: Clone Repo2
        uses: actions/checkout@v3
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          path: ./repo2

      - name: Update Repo1
        run: git pull -u origin prod && echo "Updated Repo1 from prod branch" || echo "Failed to update Repo1"

      - name: Push to Repo2 (prod branch)
        run: git push origin prod && echo "Successfully pushed to Repo2" || echo "Failed to push to Repo2"
