name: deploy-code

on:
  push:
    branches:
      - prod # Change this to your main branch

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          path: 'repo1'
          ref: prod
          persist-credentials: false
      
      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          token: ${{secrets.DEPLOY_TOKEN}}
          path: 'repo2'
          ref: main
          persist-credentials: true

      - name: Copy code from repo1 to repo2
        run: |
          cp -r repo1/* repo2/
          cd repo2
          git config user.email "divyjaiin161@gmail.com"
          git config user.name "DivyJain23"
          git add .
          git commit -m "Update from repo1 ($(date))"
          git push origin HEAD:prod
