name: deploy-code

on:
  push:
    branches:
      - prod # Change this to your main branch

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        env:
          DEPLOY_TOKEN: '${{ secrets.DEPLOY_TOKEN }}'
      
      - name: Clone repo2
        run: |
          git config --global user.email "divyjaiin161@gmail.com"
          git config --global user.name "DivyJain23"
          git config --global credential.helper cache
          if [ -d "repo2" ]; then
            rm -rf repo2
          fi
          git clone https://${{secrets.DEPLOY_TOKEN}}@github.com/DivyJain23/repo2.git

      - name: Copy code from repo1 to repo2
        run: |
          shopt -s dotglob
          cp -r !(repo2) repo2/
          cd repo2
          git add .
          git commit -m "Update from repo1 ($(date))"
          git push
