name: Push to Repo2 on Prod Merge

on:
  push:
    branches:
      - prod

jobs:
  push_to_repo2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
      
      - name: Install and configure deploy token authentication
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install curl
          sudo apt install -y software-properties-common
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
      
      - name: Configure authentication with deploy token
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          gh auth login --with-token <<<"$DEPLOY_TOKEN"
      
      - name: Clone Repo2
        uses: actions/checkout@v2
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          path: ./repo2

      - name: Push changes to Repo2 (prod branch)
        working-directory: ./repo2
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git pull origin prod --ff-only
          git push origin prod
