name: Push to Repo2 on Prod Merge

on:
  push:
    branches:
      - prod

jobs:
  push_to_repo2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install required action for deploy token authentication
        uses: apps/app-auth@v2  # Using the official GitHub Apps action


      - name: Configure authentication with deploy token
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          echo "$DEPLOY_TOKEN" | gh auth login --with-token  # Using the gh CLI from the GitHub Apps action

      - name: Clone Repo2
        uses: actions/checkout@v3
        with:
          repository: DivyJain23/repo2 # Replace with your repo2 details
          path: ./repo2

      - name: Update Repo1
        run: git pull

      - name: Push to Repo2 (prod branch)
        run: git push origin prod

